const express=require('express')
const router=express.Router()
const {registerUser,loginUser, logoutUser, forgotPassword, resetPassword, userProfile, userUpdatePassword, updateProfile}=require('../controllers/userController')
const { isAuthenticatedUser } = require('../middlewares/user')
router.route('/user/create').post(registerUser)
router.route('/user/login').post(loginUser)
router.route('/user/logout').get(logoutUser)
router.route('/user/password/forgot').post(forgotPassword)
router.route('/user/password/reset/:token').put(resetPassword)
router.route('/me').get(isAuthenticatedUser,userProfile)
router.route('/user/update-password').put(isAuthenticatedUser,userUpdatePassword)
router.route('/user/update-profile').put(isAuthenticatedUser,updateProfile)
module.exports=router;
